<a href="https://www.kaggle.com/code/axjh03/drugclassification-randomforest-99-accuracy?scriptVersionId=132997266" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score

In [2]:
def CheckNullPoints(DataFrame_Name, Column_name, values=False):
    if ((DataFrame_Name[Column_name].isna().sum() > 0)and (values==True)):
        print(f"{Column_name} has {DataFrame_Name[Column_name].isna().sum()} null points")
    elif ((DataFrame_Name[Column_name].isna().sum() > 0)and values==False):
        print(f"{Column_name} has null points")
    else:
        print(f"{Column_name} doesn't have any null points")

In [3]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/drug200csv/drug200.csv


In [4]:
df=pd.read_csv("/kaggle/input/drug200csv/drug200.csv")

In [5]:
df.head()


Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [6]:
df.keys()

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [7]:
key = df.keys() 
for k in key:
    CheckNullPoints(df, str(k), values=True)

Age doesn't have any null points
Sex doesn't have any null points
BP doesn't have any null points
Cholesterol doesn't have any null points
Na_to_K doesn't have any null points
Drug doesn't have any null points


In [8]:
def differentStringFinder(df, columnName, uniqueValuesList):
    for i in range(len(df.index)):
        if df[columnName][i] not in uniqueValuesList:
            uniqueValuesList.append(df[columnName][i])
    return uniqueValuesList

In [9]:
UniqueDrugNames = []
differentStringFinder(df, "Drug", UniqueDrugNames)
UniqueDrugNames

['drugY', 'drugC', 'drugX', 'drugA', 'drugB']

In [10]:
UniqueCholestrol_values = []
differentStringFinder(df, "Cholesterol", UniqueCholestrol_values)
UniqueCholestrol_values

['HIGH', 'NORMAL']

In [11]:
UniqueBP_values = []
differentStringFinder(df, "BP", UniqueBP_values)
UniqueBP_values

['HIGH', 'LOW', 'NORMAL']

In [12]:
# df.Drug,_ = pd.factorize(df.Drug)
df.Drug, label_mapping = pd.factorize(df.Drug)


In [13]:
df

Age Sex      BP Cholesterol  Na_to_K  Drug
0     23   F    HIGH        HIGH   25.355     0
1     47   M     LOW        HIGH   13.093     1
2     47   M     LOW        HIGH   10.114     1
3     28   F  NORMAL        HIGH    7.798     2
4     61   F     LOW        HIGH   18.043     0
..   ...  ..     ...         ...      ...   ...
195   56   F     LOW        HIGH   11.567     1
196   16   M     LOW        HIGH   12.006     1
197   52   M  NORMAL        HIGH    9.894     2
198   23   M  NORMAL      NORMAL   14.020     2
199   40   F     LOW      NORMAL   11.349     2

[200 rows x 6 columns]

In [14]:
df.Sex,_ = pd.factorize(df.Sex)
df.BP,_ = pd.factorize(df.BP)
df.Cholesterol,_ = pd.factorize(df.Cholesterol)

In [15]:
df

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0     23    0   0            0   25.355     0
1     47    1   1            0   13.093     1
2     47    1   1            0   10.114     1
3     28    0   2            0    7.798     2
4     61    0   1            0   18.043     0
..   ...  ...  ..          ...      ...   ...
195   56    0   1            0   11.567     1
196   16    1   1            0   12.006     1
197   52    1   2            0    9.894     2
198   23    1   2            1   14.020     2
199   40    0   1            1   11.349     2

[200 rows x 6 columns]

In [16]:
featuresToTrain = list(df.keys())
featuresToTrain.remove("Drug")
featuresToTrain

['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(df[featuresToTrain], df["Drug"], train_size=0.8, shuffle=True)

In [18]:
RF_model = RandomForestRegressor()

In [19]:
RF_model.fit(X_train, y_train)

RandomForestRegressor()

In [20]:
y_pred = RF_model.predict(X_test)

In [21]:
label_encoder = LabelEncoder()
label_encoder.fit(df['Drug'])

LabelEncoder()

In [22]:
# Prepare the input features for prediction
new_features = [[47, 0, 0, 0, 13]]  # Example input features (age, sex, BP, Cholesterol, Na_to_K)

# Make predictions
predicted_label = RF_model.predict(new_features)

match int(predicted_label):
    case 0:
        print("DrugY")
    case 1:
        print("DrugC")
    case 2:
        print("DrugX")
    case 3:
        print("DrugA")
    case 4:
        print("DrugB")


DrugA


/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


In [23]:
SexList = np.array(df.Sex)
BPList = np.array(df.BP)
CList = np.array(df.Cholesterol)

In [24]:
print(SexList[:25])
print(BPList[:25])
print(CList[:25])

[0 1 1 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 1 0 0]
[0 1 1 2 1 2 2 1 2 1 1 0 1 1 2 0 1 0 1 0 1 2 1 1 1]
[0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 1 0 0]


In [25]:
accuracy = r2_score(y_test, y_pred)
print("Accuracy score:", accuracy)

Accuracy score: 0.9999749117992944
